version: 0.2

phases:
  install:
    commands:
       # Nothing to install.....
       
  pre_build:
      commands:
       #echo "Logging in to Amazon ECR..."
      - aws --region ${AWS_REGION} ecr get-login-password  | docker login --password-stdin  --username AWS "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
  build:
    commands:
      - docker build --tag $REPOSITORY_URI:latest . 
      

  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest 
      - echo Writing image definitions file...
      - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
