version: 0.2

phases:
  install:
    commands:
       # Nothing to install.....
       
  pre_build:
      commands:
       #echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin $(echo $CODEBUILD_BUILD_ARN | cut -f5 -d ':').dkr.ecr.${AWS_REGION}.amazonaws.com
  build:
    commands:
     - echo $REPOSITORY_URI
     - docker build -t 334902933163.dkr.ecr.us-east-1.amazonaws.com/ecs-docker-repo:latest .
      

  post_build:
    commands:
      - docker push 334902933163.dkr.ecr.us-east-1.amazonaws.com/ecs-docker-repo:latest 
      - echo Writing image definitions file...
      - printf '{"ImageURI":"%s"}' 334902933163.dkr.ecr.us-east-1.amazonaws.com/ecs-docker-repo:latest > $CODEBUILD_SRC_DIR/imagedefinitions.json
      
artifacts:
    files: 
      - imagedefinitions.json
